version: '3.8'
services:
    super_mysqldb:
        image: mysql/mysql-server:8.0.23
        container_name: super_db_prod
        env_file: ./.env
        environment: 
            MYSQL_TCP_PORT: $MYSQL_DOCKER_PORT
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_HOST: "%"
        ports: 
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes:
            - mysql_prod:/var/lib/mysql
            - mysql_config_prod:/etc/mysql

    super_backend:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file: ./.env
        ports: 
            - $HTTP_REPLICA_PORTS:$HTTP_PORT
        command: npm run start:prod
        scale: $API_REPLICAS

volumes:
    mysql_prod:
    mysql_config_prod:
