version: '3.8'
services:
    super_mysqldb:
        image: mysql/mysql-server:8.0.23
        container_name: super_db_dev
        env_file: ./.env
        environment: 
            MYSQL_TCP_PORT: $MYSQL_DOCKER_PORT
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_HOST: "%"
        ports: 
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

    super_backend:
        container_name: super_api_dev
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        command: npm start

volumes:
    mysql:
    mysql_config:
