version: '3.8'
services:
    super_mysqldb:
        image: mysql/mysql-server:8.0.23
        container_name: super_db_prod
        env_file: ./.env
        environment: 
            MYSQL_TCP_PORT: $MYSQL_DOCKER_PORT
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_HOST: "%"
        ports: 
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

    super_backend:
        container_name: super_api_prod
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file: ./.env
        ports: 
            - $HTTP_PORT:$HTTP_PORT
        command: npm run start:prod

volumes:
    mysql:
    mysql_config:
    node_modules:
