pipeline {
    agent { 
        node {
            label 'alpine-docker-agent'
            }
      }
    stages {
        stage('Build') {
            steps {
                echo "Building..."
                sh "make build up"
            }
        }
        stage('Database') {
            steps {
                echo "DB operations"
                sh 'make db-migrate'
                sh 'make db-seed'
                sh 'make db-populate'
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                echo "doing test stuff..
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}